services:
  # web:
  #   build: .
  #   command: python manage.py runserver 0.0.0.0:8000
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - .:/code
  db:
    image: postgres:14.6-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.11.5
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"
      - "16379:16379"
      - "26379:26379"
  celery_worker:
    build: .
    command: celery -A sentiment worker --pool=solo --loglevel=INFO
    volumes:
     - .:/code
    depends_on:
      - db
      - rabbitmq
      - redis
volumes:
  db:
    driver: local
