# Development environment
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      ALLOWED_HOSTS: web,localhost
      CELERY_HOST: rabbitmq
      DB_HOST: db
  db:
    image: postgres:14.6-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
  rabbitmq:
    image: rabbitmq:3.11.5-management
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: "redis:7-alpine"
  celery_worker:
    build: .
    command: celery -A sentiment worker --pool=solo --loglevel=INFO
    volumes:
      - .:/code
    environment:
      CELERY_HOST: rabbitmq
      DB_HOST: db
    depends_on:
      - db
      - rabbitmq
      - redis
volumes:
  db:
    driver: local
