# Generated by Django 4.1.4 on 2022-12-18 06:30

from django.db import migrations, models
from django.contrib.postgres.fields import ArrayField

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(null=False)),
                ('score', models.FloatField(null=False)),
                ('tags', ArrayField(base_field=models.TextField(null=False), size=None)),
                ('text', models.TextField(null=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
